<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE de [
<!ELEMENT de (pair+)>
<!ELEMENT pair (key, value)>
<!ELEMENT key (#PCDATA)>
<!ELEMENT value (#PCDATA)>
]>
<de>
	<pair>
		<key>PLAY_OFFLINE</key>
		<value>offline spielen</value>
	</pair>
	<pair>
		<key>PLAY_ONLINE</key>
		<value>online spielen</value>
	</pair>
	<pair>
		<key>SETTINGS</key>
		<value>einstellungen</value>
	</pair>
	<pair>
		<key>RULES</key>
		<value>regeln</value>
	</pair>
	
	
	
	<pair>
		<key>EXIT</key>
		<value>beenden</value>
	</pair>
	
	
	
	
	
	<pair>
		<key>MASTER</key>
		<value>gesamt</value>
	</pair>
	<pair>
		<key>MUSIC</key>
		<value>musik</value>
	</pair>
	<pair>
		<key>SFX</key>
		<value>SFX</value>
	</pair>
	<pair>
		<key>OK</key>
		<value>fertig</value>
	</pair>
	<pair>
		<key>BACK</key>
		<value>zur√ºck</value>
	</pair>
	<pair>
		<key>NEXT</key>
		<value>neben</value>
	</pair>
	<pair>
		<key>PLAYER</key>
		<value>spieler</value>
	</pair>
	<pair>
		<key>READY</key>
		<value>bereit</value>
	</pair>
	<pair>
		<key>PLAY</key>
		<value>spiel</value>
	</pair>
	<pair>
		<key>YES</key>
		<value>ja</value>
	</pair>
	<pair>
		<key>NO</key>
		<value>nein</value>
	</pair>
	<pair>
		<key>ARE_YOU_SURE_WANT_TO_EXIT</key>
		<value>sind sie sicher, dass sie beenden wollen?</value>
	</pair>
</de>