<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vertices [
<!ELEMENT vertices (province+)>
<!ELEMENT province (name, mesh+)>
<!ELEMENT mesh (vertex+)>
<!ELEMENT vertex (x, y)>
<!ELEMENT x (#PCDATA)>
<!ELEMENT y (#PCDATA)>
]>
<vertices>
	<province>
		<name>alaska</name>
		<mesh>
			<vertex><x>45</x><y>199</y></vertex>
			<vertex><x>51</x><y>199</y></vertex>
			<vertex><x>55</x><y>198</y></vertex>
			<vertex><x>58</x><y>197</y></vertex>
			<vertex><x>61</x><y>194</y></vertex>
			<vertex><x>64</x><y>191</y></vertex>
			<vertex><x>66</x><y>190</y></vertex>
			<vertex><x>68</x><y>191</y></vertex>
			<vertex><x>71</x><y>190</y></vertex>
			<vertex><x>74</x><y>189</y></vertex>
			<vertex><x>75</x><y>188</y></vertex>
			<vertex><x>76</x><y>190</y></vertex>
			<vertex><x>78</x><y>190</y></vertex>
			<vertex><x>77</x><y>188</y></vertex>
			<vertex><x>79</x><y>187</y></vertex>
			<vertex><x>80</x><y>188</y></vertex>
			<vertex><x>82</x><y>187</y></vertex>
			<vertex><x>85</x><y>187</y></vertex>
			<vertex><x>88</x><y>186</y></vertex>
			<vertex><x>91</x><y>185</y></vertex>
			<vertex><x>94</x><y>183</y></vertex>
			<vertex><x>97</x><y>185</y></vertex>
			<vertex><x>96</x><y>186</y></vertex>
			<vertex><x>97</x><y>187</y></vertex>
			<vertex><x>100</x><y>186</y></vertex>
			<vertex><x>101</x><y>185</y></vertex>
			<vertex><x>103</x><y>185</y></vertex>
			<vertex><x>103</x><y>186</y></vertex>
			<vertex><x>104</x><y>187</y></vertex>
			<vertex><x>107</x><y>187</y></vertex>
			<vertex><x>108</x><y>186</y></vertex>
			<vertex><x>112</x><y>186</y></vertex>
			<vertex><x>115</x><y>187</y></vertex>
			<vertex><x>115</x><y>188</y></vertex>
			<vertex><x>118</x><y>189</y></vertex>
			<vertex><x>121</x><y>190</y></vertex>
			<vertex><x>123</x><y>189</y></vertex>
			<vertex><x>134</x><y>189</y></vertex>
			<vertex><x>139</x><y>190</y></vertex>
			<vertex><x>150</x><y>191</y></vertex>
			<vertex><x>153</x><y>192</y></vertex>
			<vertex><x>156</x><y>192</y></vertex>
			<vertex><x>159</x><y>191</y></vertex>
			<vertex><x>165</x><y>191</y></vertex>
			<vertex><x>167</x><y>192</y></vertex>
			<vertex><x>169</x><y>193</y></vertex>
			<vertex><x>171</x><y>193</y></vertex>
			<vertex><x>172</x><y>194</y></vertex>
			<vertex><x>176</x><y>195</y></vertex>
			<vertex><x>179</x><y>194</y></vertex>
			<vertex><x>181</x><y>195</y></vertex>
			<vertex><x>184</x><y>194</y></vertex>
			<vertex><x>186</x><y>196</y></vertex>
			<vertex><x>189</x><y>197</y></vertex>
			<vertex><x>192</x><y>198</y></vertex>
			<vertex><x>195</x><y>199</y></vertex>
			<vertex><x>200</x><y>199</y></vertex>
			<vertex><x>201</x><y>200</y></vertex>
			<vertex><x>203</x><y>199</y></vertex>
			<vertex><x>202</x><y>197</y></vertex>
			<vertex><x>205</x><y>195</y></vertex>
			<vertex><x>209</x><y>194</y></vertex>
			<vertex><x>211</x><y>195</y></vertex>
			<vertex><x>209</x><y>196</y></vertex>
			<vertex><x>206</x><y>198</y></vertex>
			<vertex><x>206</x><y>200</y></vertex>
			<vertex><x>208</x><y>199</y></vertex>
			<vertex><x>211</x><y>197</y></vertex>
			<vertex><x>212</x><y>196</y></vertex>
			<vertex><x>215</x><y>196</y></vertex>
			<vertex><x>217</x><y>194</y></vertex>
			<vertex><x>222</x><y>193</y></vertex>
			<vertex><x>225</x><y>193</y></vertex>
			<vertex><x>227</x><y>191</y></vertex>
			<vertex><x>229</x><y>191</y></vertex>
			<vertex><x>233</x><y>191</y></vertex>
			<vertex><x>233</x><y>192</y></vertex>
			<vertex><x>231</x><y>192</y></vertex>
			<vertex><x>228</x><y>193</y></vertex>
			<vertex><x>226</x><y>194</y></vertex>
			<vertex><x>223</x><y>194</y></vertex>
			<vertex><x>221</x><y>194</y></vertex>
			<vertex><x>220</x><y>195</y></vertex>
			<vertex><x>217</x><y>196</y></vertex>
			<vertex><x>216</x><y>197</y></vertex>
			<vertex><x>214</x><y>198</y></vertex>
			<vertex><x>215</x><y>200</y></vertex>
			<vertex><x>214</x><y>202</y></vertex>
			<vertex><x>214</x><y>204</y></vertex>
			<vertex><x>212</x><y>206</y></vertex>
			<vertex><x>211</x><y>207</y></vertex>
			<vertex><x>210</x><y>209</y></vertex>
			<vertex><x>209</x><y>211</y></vertex>
			<vertex><x>208</x><y>212</y></vertex>
			<vertex><x>207</x><y>214</y></vertex>
			<vertex><x>206</x><y>216</y></vertex>
			<vertex><x>205</x><y>217</y></vertex>
			<vertex><x>203</x><y>221</y></vertex>
			<vertex><x>202</x><y>222</y></vertex>
			<vertex><x>201</x><y>224</y></vertex>
			<vertex><x>200</x><y>225</y></vertex>
			<vertex><x>199</x><y>227</y></vertex>
			<vertex><x>198</x><y>229</y></vertex>
			<vertex><x>197</x><y>230</y></vertex>
			<vertex><x>196</x><y>232</y></vertex>
			<vertex><x>195</x><y>233</y></vertex>
			<vertex><x>194</x><y>235</y></vertex>
			<vertex><x>193</x><y>237</y></vertex>
			<vertex><x>192</x><y>238</y></vertex>
			<vertex><x>191</x><y>240</y></vertex>
			<vertex><x>190</x><y>242</y></vertex>
			<vertex><x>189</x><y>244</y></vertex>
			<vertex><x>189</x><y>248</y></vertex>
			<vertex><x>188</x><y>251</y></vertex>
			<vertex><x>193</x><y>251</y></vertex>
			<vertex><x>194</x><y>252</y></vertex>
			<vertex><x>198</x><y>252</y></vertex>
			<vertex><x>204</x><y>255</y></vertex>
			<vertex><x>211</x><y>261</y></vertex>
			<vertex><x>212</x><y>262</y></vertex>
			<vertex><x>213</x><y>264</y></vertex>
			<vertex><x>214</x><y>266</y></vertex>
			<vertex><x>214</x><y>267</y></vertex>
			<vertex><x>213</x><y>267</y></vertex>
			<vertex><x>211</x><y>265</y></vertex>
			<vertex><x>209</x><y>264</y></vertex>
			<vertex><x>137</x><y>247</y></vertex>
			<vertex><x>118</x><y>258</y></vertex>
			<vertex><x>130</x><y>244</y></vertex>
			<vertex><x>106</x><y>259</y></vertex>
			<vertex><x>110</x><y>260</y></vertex>
			<vertex><x>51</x><y>288</y></vertex>
			<vertex><x>91</x><y>261</y></vertex>
			<vertex><x>66</x><y>262</y></vertex>
			<vertex><x>64</x><y>250</y></vertex>
			<vertex><x>55</x><y>255</y></vertex>
			<vertex><x>44</x><y>244</y></vertex>
			<vertex><x>53</x><y>234</y></vertex>
			<vertex><x>71</x><y>230</y></vertex>
			<vertex><x>71</x><y>224</y></vertex>
			<vertex><x>43</x><y>225</y></vertex>
			<vertex><x>34</x><y>219</y></vertex>
			<vertex><x>56</x><y>212</y></vertex>
			<vertex><x>56</x><y>216</y></vertex>
			<vertex><x>74</x><y>213</y></vertex>
			<vertex><x>42</x><y>202</y></vertex>
		</mesh>
	</province>
	<province>
		<name>northwest territory</name>
		<mesh>
			<vertex><x>215</x><y>199</y></vertex>
			<vertex><x>241</x><y>188</y></vertex>
			<vertex><x>255</x><y>195</y></vertex>
			<vertex><x>259</x><y>190</y></vertex>
			<vertex><x>260</x><y>195</y></vertex>
			<vertex><x>267</x><y>193</y></vertex>
			<vertex><x>303</x><y>198</y></vertex>
			<vertex><x>314</x><y>202</y></vertex>
			<vertex><x>307</x><y>205</y></vertex>
			<vertex><x>334</x><y>204</y></vertex>
			<vertex><x>348</x><y>213</y></vertex>
			<vertex><x>342</x><y>202</y></vertex>
			<vertex><x>358</x><y>201</y></vertex>
			<vertex><x>411</x><y>167</y></vertex>
			<vertex><x>436</x><y>167</y></vertex>
			<vertex><x>418</x><y>181</y></vertex>
			<vertex><x>437</x><y>202</y></vertex>
			<vertex><x>442</x><y>196</y></vertex>
			<vertex><x>449</x><y>203</y></vertex>
			<vertex><x>452</x><y>209</y></vertex>
			<vertex><x>462</x><y>192</y></vertex>
			<vertex><x>484</x><y>199</y></vertex>
			<vertex><x>483</x><y>207</y></vertex>
			<vertex><x>414</x><y>250</y></vertex>
			<vertex><x>200</x><y>251</y></vertex>
			<vertex><x>190</x><y>249</y></vertex>
			<vertex><x>187</x><y>246</y></vertex>
		</mesh>
	</province>
	<province>
		<name>alberta</name>
		<mesh>
			<vertex><x>197</x><y>251</y></vertex>
			<vertex><x>398</x><y>251</y></vertex>
			<vertex><x>365</x><y>334</y></vertex>
			<vertex><x>262</x><y>334</y></vertex>
		</mesh>
	</province>
	<province>
		<name>ontario</name>
		<mesh>
			<vertex><x>398</x><y>251</y></vertex>
			<vertex><x>414</x><y>250</y></vertex>
			<vertex><x>414</x><y>260</y></vertex>
			<vertex><x>422</x><y>261</y></vertex>
			<vertex><x>425</x><y>273</y></vertex>
			<vertex><x>434</x><y>270</y></vertex>
			<vertex><x>478</x><y>284</y></vertex>
			<vertex><x>479</x><y>297</y></vertex>
			<vertex><x>490</x><y>308</y></vertex>
			<vertex><x>485</x><y>330</y></vertex>
			<vertex><x>513</x><y>350</y></vertex>
			<vertex><x>474</x><y>366</y></vertex>
			<vertex><x>491</x><y>348</y></vertex>
			<vertex><x>469</x><y>338</y></vertex>
			<vertex><x>456</x><y>323</y></vertex>
			<vertex><x>448</x><y>322</y></vertex>
			<vertex><x>428</x><y>334</y></vertex>
			<vertex><x>365</x><y>333</y></vertex>
		</mesh>
	</province>
	<province>
		<name>quebec</name>
		<mesh>
			<vertex><x>490</x><y>309</y></vertex>
			<vertex><x>492</x><y>287</y></vertex>
			<vertex><x>507</x><y>277</y></vertex>
			<vertex><x>506</x><y>267</y></vertex>
			<vertex><x>497</x><y>261</y></vertex>
			<vertex><x>504</x><y>255</y></vertex>
			<vertex><x>500</x><y>248</y></vertex>
			<vertex><x>503</x><y>244</y></vertex>
			<vertex><x>499</x><y>239</y></vertex>
			<vertex><x>503</x><y>237</y></vertex>
			<vertex><x>517</x><y>239</y></vertex>
			<vertex><x>522</x><y>238</y></vertex>
			<vertex><x>545</x><y>247</y></vertex>
			<vertex><x>550</x><y>261</y></vertex>
			<vertex><x>554</x><y>266</y></vertex>
			<vertex><x>570</x><y>251</y></vertex>
			<vertex><x>607</x><y>287</y></vertex>
			<vertex><x>592</x><y>295</y></vertex>
			<vertex><x>603</x><y>290</y></vertex>
			<vertex><x>616</x><y>296</y></vertex>
			<vertex><x>615</x><y>304</y></vertex>
			<vertex><x>609</x><y>307</y></vertex>
			<vertex><x>600</x><y>308</y></vertex>
			<vertex><x>593</x><y>314</y></vertex>
			<vertex><x>559</x><y>315</y></vertex>
			<vertex><x>556</x><y>320</y></vertex>
			<vertex><x>551</x><y>321</y></vertex>
			<vertex><x>536</x><y>335</y></vertex>
			<vertex><x>544</x><y>329</y></vertex>
			<vertex><x>562</x><y>321</y></vertex>
			<vertex><x>572</x><y>324</y></vertex>
			<vertex><x>566</x><y>328</y></vertex>
			<vertex><x>559</x><y>328</y></vertex>
			<vertex><x>564</x><y>330</y></vertex>
			<vertex><x>569</x><y>330</y></vertex>
			<vertex><x>568</x><y>334</y></vertex>
			<vertex><x>570</x><y>339</y></vertex>
			<vertex><x>583</x><y>341</y></vertex>
			<vertex><x>591</x><y>334</y></vertex>
			<vertex><x>594</x><y>340</y></vertex>
			<vertex><x>564</x><y>356</y></vertex>
			<vertex><x>562</x><y>354</y></vertex>
			<vertex><x>563</x><y>349</y></vertex>
			<vertex><x>575</x><y>345</y></vertex>
			<vertex><x>568</x><y>345</y></vertex>
			<vertex><x>570</x><y>342</y></vertex>
			<vertex><x>541</x><y>355</y></vertex>
			<vertex><x>538</x><y>345</y></vertex>
			<vertex><x>516</x><y>350</y></vertex>
			<vertex><x>485</x><y>331</y></vertex>
		</mesh>
	</province>
	<province>
		<name>western united states</name>
		<mesh>
			<vertex><x>00000</x><y>00000</y></vertex>
		</mesh>
	</province>
	<province>
		<name>eastern united states</name>
		<mesh>
			<vertex><x>00000</x><y>00000</y></vertex>
		</mesh>
	</province>
	<province>
		<name>central america</name>
		<mesh>
			<vertex><x>00000</x><y>00000</y></vertex>
		</mesh>
	</province>
	<province>
		<name>greenland</name>
		<mesh>
			<vertex><x>552</x><y>132</y></vertex>
			<vertex><x>554</x><y>130</y></vertex>
			<vertex><x>579</x><y>126</y></vertex>
			<vertex><x>585</x><y>123</y></vertex>
			<vertex><x>584</x><y>120</y></vertex>
			<vertex><x>589</x><y>120</y></vertex>
			<vertex><x>574</x><y>118</y></vertex>
			<vertex><x>591</x><y>113</y></vertex>
			<vertex><x>600</x><y>113</y></vertex>
			<vertex><x>600</x><y>109</y></vertex>
			<vertex><x>628</x><y>105</y></vertex>
			<vertex><x>641</x><y>104</y></vertex>
			<vertex><x>668</x><y>108</y></vertex>
			<vertex><x>666</x><y>107</y></vertex>
			<vertex><x>667</x><y>106</y></vertex>
			<vertex><x>676</x><y>106</y></vertex>
			<vertex><x>663</x><y>102</y></vertex>
			<vertex><x>685</x><y>104</y></vertex>
			<vertex><x>658</x><y>101</y></vertex>
			<vertex><x>673</x><y>99</y></vertex>
			<vertex><x>690</x><y>102</y></vertex>
			<vertex><x>695</x><y>100</y></vertex>
			<vertex><x>690</x><y>98</y></vertex>
			<vertex><x>743</x><y>99</y></vertex>
			<vertex><x>704</x><y>102</y></vertex>
			<vertex><x>746</x><y>100</y></vertex>
			<vertex><x>745</x><y>102</y></vertex>
			<vertex><x>760</x><y>103</y></vertex>
			<vertex><x>714</x><y>109</y></vertex>
			<vertex><x>745</x><y>107</y></vertex>
			<vertex><x>737</x><y>111</y></vertex>
			<vertex><x>750</x><y>107</y></vertex>
			<vertex><x>757</x><y>107</y></vertex>
			<vertex><x>757</x><y>111</y></vertex>
			<vertex><x>749</x><y>116</y></vertex>
			<vertex><x>766</x><y>109</y></vertex>
			<vertex><x>773</x><y>111</y></vertex>
			<vertex><x>777</x><y>108</y></vertex>
			<vertex><x>798</x><y>110</y></vertex>
			<vertex><x>762</x><y>117</y></vertex>
			<vertex><x>782</x><y>117</y></vertex>
			<vertex><x>778</x><y>119</y></vertex>
			<vertex><x>767</x><y>118</y></vertex>
			<vertex><x>764</x><y>121</y></vertex>
			<vertex><x>777</x><y>120</y></vertex>
			<vertex><x>771</x><y>125</y></vertex>
			<vertex><x>759</x><y>135</y></vertex>
			<vertex><x>770</x><y>136</y></vertex>
			<vertex><x>764</x><y>135</y></vertex>
			<vertex><x>774</x><y>139</y></vertex>
			<vertex><x>756</x><y>142</y></vertex>
			<vertex><x>767</x><y>146</y></vertex>
			<vertex><x>770</x><y>156</y></vertex>
			<vertex><x>760</x><y>183</y></vertex>
			<vertex><x>758</x><y>184</y></vertex>
			<vertex><x>744</x><y>192</y></vertex>
			<vertex><x>720</x><y>198</y></vertex>
			<vertex><x>716</x><y>194</y></vertex>
			<vertex><x>718</x><y>199</y></vertex>
			<vertex><x>706</x><y>209</y></vertex>
			<vertex><x>694</x><y>214</y></vertex>
			<vertex><x>696</x><y>209</y></vertex>
			<vertex><x>694</x><y>209</y></vertex>
			<vertex><x>692</x><y>213</y></vertex>
			<vertex><x>685</x><y>214</y></vertex>
			<vertex><x>669</x><y>251</y></vertex>
			<vertex><x>653</x><y>246</y></vertex>
			<vertex><x>637</x><y>223</y></vertex>
			<vertex><x>630</x><y>210</y></vertex>
			<vertex><x>630</x><y>199</y></vertex>
			<vertex><x>641</x><y>194</y></vertex>
			<vertex><x>640</x><y>185</y></vertex>
			<vertex><x>626</x><y>181</y></vertex>
			<vertex><x>642</x><y>183</y></vertex>
			<vertex><x>623</x><y>176</y></vertex>
			<vertex><x>626</x><y>166</y></vertex>
			<vertex><x>611</x><y>149</y></vertex>
			<vertex><x>591</x><y>144</y></vertex>
			<vertex><x>566</x><y>144</y></vertex>
			<vertex><x>572</x><y>142</y></vertex>
			<vertex><x>558</x><y>140</y></vertex>
			<vertex><x>578</x><y>139</y></vertex>
			<vertex><x>579</x><y>136</y></vertex>
			<vertex><x>566</x><y>137</y></vertex>
		</mesh>
	</province>
	<!-- CAÄžRI'S PART -->
	<province>
		<name>scandinavia</name>
		<mesh>
			<vertex><x>1064</x><y>189</y></vertex>
			<vertex><x>1055</x><y>187</y></vertex>
			<vertex><x>1043</x><y>187</y></vertex>
			<vertex><x>1033</x><y>187</y></vertex>
			<vertex><x>1020</x><y>188</y></vertex>
			<vertex><x>1013</x><y>193</y></vertex>
			<vertex><x>1002</x><y>192</y></vertex>
			<vertex><x>994</x><y>196</y></vertex>
			<vertex><x>982</x><y>199</y></vertex>
			<vertex><x>979</x><y>204</y></vertex>
			<vertex><x>980</x><y>209</y></vertex>
			<vertex><x>973</x><y>214</y></vertex>
			<vertex><x>970</x><y>220</y></vertex>
			<vertex><x>969</x><y>222</y></vertex>
			<vertex><x>972</x><y>228</y></vertex>
			<vertex><x>955</x><y>230</y></vertex>
			<vertex><x>938</x><y>237</y></vertex>
			<vertex><x>932</x><y>242</y></vertex>
			<vertex><x>931</x><y>252</y></vertex>
			<vertex><x>933</x><y>262</y></vertex>
			<vertex><x>944</x><y>266</y></vertex>
			<vertex><x>957</x><y>259</y></vertex>
			<vertex><x>960</x><y>254</y></vertex>
			<vertex><x>963</x><y>265</y></vertex>
			<vertex><x>968</x><y>273</y></vertex>
			<vertex><x>971</x><y>279</y></vertex>
			<vertex><x>971</x><y>283</y></vertex>
			<vertex><x>978</x><y>282</y></vertex>
			<vertex><x>981</x><y>278</y></vertex>
			<vertex><x>987</x><y>282</y></vertex>
			<vertex><x>991</x><y>264</y></vertex>
			<vertex><x>999</x><y>259</y></vertex>
			<vertex><x>1001</x><y>256</y></vertex>
			<vertex><x>1001</x><y>252</y></vertex>
			<vertex><x>994</x><y>249</y></vertex>
			<vertex><x>995</x><y>239</y></vertex>
			<vertex><x>1014</x><y>227</y></vertex>
			<vertex><x>1020</x><y>218</y></vertex>
			<vertex><x>1033</x><y>218</y></vertex>
			<vertex><x>1035</x><y>220</y></vertex>
			<vertex><x>1035</x><y>223</y></vertex>
			<vertex><x>1017</x><y>234</y></vertex>
			<vertex><x>1014</x><y>238</y></vertex>
			<vertex><x>1016</x><y>247</y></vertex>
			<vertex><x>1024</x><y>254</y></vertex>
			<vertex><x>1040</x><y>251</y></vertex>
			<vertex><x>1052</x><y>250</y></vertex>
			<vertex><x>1065</x><y>253</y></vertex>
			<vertex><x>1061</x><y>247</y></vertex>
			<vertex><x>1068</x><y>237</y></vertex>
			<vertex><x>1064</x><y>216</y></vertex>
			<vertex><x>1057</x><y>208</y></vertex>
			<vertex><x>1059</x><y>192</y></vertex>

		</mesh>
	</province>
	<province>
		<name>ukraine</name>
		<mesh>
			<vertex><x>1053</x><y>257</y></vertex>
			<vertex><x>1036</x><y>257</y></vertex>
			<vertex><x>1027</x><y>259</y></vertex>
			<vertex><x>1028</x><y>264</y></vertex>
			<vertex><x>1031</x><y>271</y></vertex>
			<vertex><x>1025</x><y>271</y></vertex>
			<vertex><x>1018</x><y>269</y></vertex>
			<vertex><x>1014</x><y>274</y></vertex>
			<vertex><x>1015</x><y>286</y></vertex>
			<vertex><x>1009</x><y>286</y></vertex>
			<vertex><x>1008</x><y>290</y></vertex>
			<vertex><x>1001</x><y>287</y></vertex>
			<vertex><x>991</x><y>288</y></vertex>
			<vertex><x>991</x><y>291</y></vertex>
			<vertex><x>971</x><y>288</y></vertex>
			<vertex><x>1020</x><y>301</y></vertex>
			<vertex><x>1026</x><y>310</y></vertex>
			<vertex><x>1017</x><y>318</y></vertex>
			<vertex><x>1017</x><y>325</y></vertex>
			<vertex><x>1027</x><y>332</y></vertex>
			<vertex><x>1043</x><y>332</y></vertex>
			<vertex><x>1058</x><y>349</y></vertex>
			<vertex><x>1066</x><y>337</y></vertex>
			<vertex><x>1079</x><y>340</y></vertex>
			<vertex><x>1074</x><y>346</y></vertex>
			<vertex><x>1092</x><y>347</y></vertex>
			<vertex><x>1086</x><y>340</y></vertex>
			<vertex><x>1107</x><y>333</y></vertex>
			<vertex><x>1096</x><y>346</y></vertex>
			<vertex><x>1172</x><y>369</y></vertex>
			<vertex><x>1156</x><y>386</y></vertex>
			<vertex><x>1164</x><y>375</y></vertex>
			<vertex><x>1148</x><y>347</y></vertex>
			<vertex><x>1135</x><y>333</y></vertex>
			<vertex><x>1143</x><y>308</y></vertex>
			<vertex><x>1159</x><y>295</y></vertex>
			<vertex><x>1150</x><y>279</y></vertex>
			<vertex><x>1156</x><y>240</y></vertex>
			<vertex><x>1146</x><y>212</y></vertex>
			<vertex><x>1139</x><y>207</y></vertex>
			<vertex><x>1120</x><y>214</y></vertex>
			<vertex><x>1096</x><y>222</y></vertex>
			<vertex><x>1102</x><y>229</y></vertex>
			<vertex><x>1086</x><y>226</y></vertex>
			<vertex><x>1085</x><y>217</y></vertex>
			<vertex><x>1074</x><y>210</y></vertex>
			<vertex><x>1113</x><y>216</y></vertex>
			<vertex><x>1118</x><y>210</y></vertex>
			<vertex><x>1090</x><y>197</y></vertex>
			<vertex><x>1060</x><y>193</y></vertex>
			<vertex><x>1057</x><y>209</y></vertex>
			<vertex><x>1070</x><y>232</y></vertex>
			<vertex><x>1064</x><y>244</y></vertex>
			<vertex><x>1075</x><y>250</y></vertex>
			<vertex><x>1066</x><y>255</y></vertex>

		</mesh>
	</province>
	<province>
		<name>iceland</name>
		<mesh>
			<vertex><x>835</x><y>219</y></vertex>
			<vertex><x>834</x><y>227</y></vertex>
			<vertex><x>826</x><y>233</y></vertex>
			<vertex><x>803</x><y>240</y></vertex>
			<vertex><x>768</x><y>237</y></vertex>
			<vertex><x>755</x><y>227</y></vertex>
			<vertex><x>757</x><y>220</y></vertex>
			<vertex><x>766</x><y>213</y></vertex>
			<vertex><x>776</x><y>217</y></vertex>
			<vertex><x>778</x><y>224</y></vertex>
			<vertex><x>783</x><y>221</y></vertex>
			<vertex><x>786</x><y>216</y></vertex>
			<vertex><x>810</x><y>217</y></vertex>
			<vertex><x>815</x><y>212</y></vertex>
			<vertex><x>827</x><y>215</y></vertex>
		</mesh>
	</province>
	<province>
		<name>western europe</name>
		<mesh>
			<vertex><x>918</x><y>311</y></vertex>
			<vertex><x>909</x><y>320</y></vertex>
			<vertex><x>904</x><y>323</y></vertex>
			<vertex><x>898</x><y>320</y></vertex>
			<vertex><x>897</x><y>325</y></vertex>
			<vertex><x>881</x><y>324</y></vertex>
			<vertex><x>885</x><y>330</y></vertex>
			<vertex><x>894</x><y>332</y></vertex>
			<vertex><x>898</x><y>339</y></vertex>
			<vertex><x>898</x><y>359</y></vertex>
			<vertex><x>864</x><y>356</y></vertex>
			<vertex><x>857</x><y>360</y></vertex>
			<vertex><x>859</x><y>376</y></vertex>
			<vertex><x>856</x><y>386</y></vertex>
			<vertex><x>858</x><y>396</y></vertex>
			<vertex><x>870</x><y>396</y></vertex>
			<vertex><x>876</x><y>403</y></vertex>
			<vertex><x>894</x><y>398</y></vertex>
			<vertex><x>906</x><y>386</y></vertex>
			<vertex><x>903</x><y>380</y></vertex>
			<vertex><x>910</x><y>371</y></vertex>
			<vertex><x>922</x><y>366</y></vertex>
			<vertex><x>920</x><y>359</y></vertex>
			<vertex><x>926</x><y>355</y></vertex>
			<vertex><x>933</x><y>358</y></vertex>
			<vertex><x>943</x><y>354</y></vertex>
			<vertex><x>938</x><y>338</y></vertex>
			<vertex><x>942</x><y>323</y></vertex>
			<vertex><x>932</x><y>320</y></vertex>
		</mesh>
	</province>
	<province>
		<name>southern europe</name>
		<mesh>
			<vertex><x>946</x><y>353</y></vertex>
			<vertex><x>952</x><y>351</y></vertex>
			<vertex><x>963</x><y>363</y></vertex>
			<vertex><x>979</x><y>374</y></vertex>
			<vertex><x>988</x><y>380</y></vertex>
			<vertex><x>987</x><y>388</y></vertex>
			<vertex><x>971</x><y>391</y></vertex>
			<vertex><x>983</x><y>399</y></vertex>
			<vertex><x>985</x><y>393</y></vertex>
			<vertex><x>994</x><y>384</y></vertex>
			<vertex><x>991</x><y>377</y></vertex>
			<vertex><x>993</x><y>375</y></vertex>
			<vertex><x>999</x><y>380</y></vertex>
			<vertex><x>1000</x><y>376</y></vertex>
			<vertex><x>987</x><y>367</y></vertex>
			<vertex><x>981</x><y>366</y></vertex>
			<vertex><x>976</x><y>361</y></vertex>
			<vertex><x>977</x><y>356</y></vertex>
			<vertex><x>969</x><y>351</y></vertex>
			<vertex><x>969</x><y>345</y></vertex>
			<vertex><x>975</x><y>343</y></vertex>
			<vertex><x>977</x><y>348</y></vertex>
			<vertex><x>987</x><y>357</y></vertex>
			<vertex><x>1006</x><y>366</y></vertex>
			<vertex><x>1006</x><y>378</y></vertex>
			<vertex><x>1014</x><y>388</y></vertex>
			<vertex><x>1018</x><y>398</y></vertex>
			<vertex><x>1024</x><y>400</y></vertex>
			<vertex><x>1029</x><y>392</y></vertex>
			<vertex><x>1025</x><y>383</y></vertex>
			<vertex><x>1022</x><y>376</y></vertex>
			<vertex><x>1029</x><y>377</y></vertex>
			<vertex><x>1036</x><y>373</y></vertex>
			<vertex><x>1041</x><y>372</y></vertex>
			<vertex><x>1056</x><y>348</y></vertex>
			<vertex><x>1044</x><y>331</y></vertex>
			<vertex><x>1024</x><y>331</y></vertex>
			<vertex><x>1015</x><y>323</y></vertex>
			<vertex><x>1002</x><y>335</y></vertex>
			<vertex><x>988</x><y>334</y></vertex>
			<vertex><x>988</x><y>324</y></vertex>
			<vertex><x>969</x><y>326</y></vertex>
			<vertex><x>957</x><y>333</y></vertex>
			<vertex><x>943</x><y>334</y></vertex>
			<vertex><x>938</x><y>340</y></vertex>
			<vertex><x>941</x><y>350</y></vertex>
		</mesh>
	</province>
	<province>
		<name>north africa</name>
		<mesh>
			<vertex><x>877</x><y>406</y></vertex>
			<vertex><x>872</x><y>417</y></vertex>
			<vertex><x>858</x><y>424</y></vertex>
			<vertex><x>854</x><y>437</y></vertex>
			<vertex><x>853</x><y>447</y></vertex>
			<vertex><x>840</x><y>454</y></vertex>
			<vertex><x>829</x><y>468</y></vertex>
			<vertex><x>818</x><y>495</y></vertex>
			<vertex><x>823</x><y>509</y></vertex>
			<vertex><x>818</x><y>532</y></vertex>
			<vertex><x>816</x><y>537</y></vertex>
			<vertex><x>821</x><y>544</y></vertex>
			<vertex><x>821</x><y>553</y></vertex>
			<vertex><x>837</x><y>571</y></vertex>
			<vertex><x>839</x><y>579</y></vertex>
			<vertex><x>864</x><y>601</y></vertex>
			<vertex><x>875</x><y>601</y></vertex>
			<vertex><x>882</x><y>595</y></vertex>
			<vertex><x>897</x><y>600</y></vertex>
			<vertex><x>915</x><y>590</y></vertex>
			<vertex><x>929</x><y>589</y></vertex>
			<vertex><x>935</x><y>601</y></vertex>
			<vertex><x>950</x><y>600</y></vertex>
			<vertex><x>959</x><y>613</y></vertex>
			<vertex><x>992</x><y>611</y></vertex>
			<vertex><x>984</x><y>596</y></vertex>
			<vertex><x>986</x><y>587</y></vertex>
			<vertex><x>1001</x><y>585</y></vertex>
			<vertex><x>1025</x><y>568</y></vertex>
			<vertex><x>1020</x><y>550</y></vertex>
			<vertex><x>1012</x><y>540</y></vertex>
			<vertex><x>1010</x><y>523</y></vertex>
			<vertex><x>1018</x><y>517</y></vertex>
			<vertex><x>1022</x><y>497</y></vertex>
			<vertex><x>1002</x><y>485</y></vertex>
			<vertex><x>976</x><y>465</y></vertex>
			<vertex><x>961</x><y>466</y></vertex>
			<vertex><x>944</x><y>458</y></vertex>
			<vertex><x>951</x><y>439</y></vertex>
			<vertex><x>957</x><y>420</y></vertex>
			<vertex><x>960</x><y>413</y></vertex>
			<vertex><x>964</x><y>410</y></vertex>
			<vertex><x>964</x><y>399</y></vertex>
			<vertex><x>956</x><y>396</y></vertex>
			<vertex><x>935</x><y>400</y></vertex>
			<vertex><x>908</x><y>402</y></vertex>
			<vertex><x>899</x><y>409</y></vertex>
			<vertex><x>888</x><y>409</y></vertex>

		</mesh>
	</province>
	<province>
		<name>east africa</name>
		<mesh>
			<vertex><x>1083</x><y>481</y></vertex>
			<vertex><x>1076</x><y>483</y></vertex>
			<vertex><x>1072</x><y>484</y></vertex>
			<vertex><x>1065</x><y>486</y></vertex>
			<vertex><x>1056</x><y>486</y></vertex>
			<vertex><x>1051</x><y>486</y></vertex>
			<vertex><x>1042</x><y>486</y></vertex>
			<vertex><x>1035</x><y>486</y></vertex>
			<vertex><x>1033</x><y>486</y></vertex>
			<vertex><x>1033</x><y>487</y></vertex>
			<vertex><x>1029</x><y>490</y></vertex>
			<vertex><x>1029</x><y>490</y></vertex>
			<vertex><x>1026</x><y>492</y></vertex>
			<vertex><x>1019</x><y>496</y></vertex>
			<vertex><x>1019</x><y>499</y></vertex>
			<vertex><x>1018</x><y>502</y></vertex>
			<vertex><x>1017</x><y>505</y></vertex>
			<vertex><x>1017</x><y>512</y></vertex>
			<vertex><x>1015</x><y>515</y></vertex>
			<vertex><x>1009</x><y>520</y></vertex>
			<vertex><x>1008</x><y>522</y></vertex>
			<vertex><x>1009</x><y>531</y></vertex>
			<vertex><x>1010</x><y>533</y></vertex>
			<vertex><x>1011</x><y>538</y></vertex>
			<vertex><x>1013</x><y>540</y></vertex>
			<vertex><x>1015</x><y>544</y></vertex>
			<vertex><x>1019</x><y>548</y></vertex>
			<vertex><x>1022</x><y>556</y></vertex>
			<vertex><x>1022</x><y>559</y></vertex>
			<vertex><x>1022</x><y>561</y></vertex>
			<vertex><x>1023</x><y>564</y></vertex>
			<vertex><x>1026</x><y>572</y></vertex>
			<vertex><x>1027</x><y>573</y></vertex>
			<vertex><x>1028</x><y>579</y></vertex>
			<vertex><x>1031</x><y>582</y></vertex>
			<vertex><x>1032</x><y>583</y></vertex>
			<vertex><x>1036</x><y>583</y></vertex>
			<vertex><x>1041</x><y>583</y></vertex>
			<vertex><x>1047</x><y>580</y></vertex>
			<vertex><x>1050</x><y>578</y></vertex>
			<vertex><x>1061</x><y>568</y></vertex>
			<vertex><x>1063</x><y>566</y></vertex>
			<vertex><x>1064</x><y>562</y></vertex>
			<vertex><x>1064</x><y>562</y></vertex>
			<vertex><x>1072</x><y>553</y></vertex>
			<vertex><x>1072</x><y>552</y></vertex>
			<vertex><x>1075</x><y>547</y></vertex>
			<vertex><x>1075</x><y>547</y></vertex>
			<vertex><x>1083</x><y>528</y></vertex>
			<vertex><x>1084</x><y>524</y></vertex>
			<vertex><x>1084</x><y>522</y></vertex>
			<vertex><x>1087</x><y>510</y></vertex>
			<vertex><x>1087</x><y>508</y></vertex>
			<vertex><x>1088</x><y>502</y></vertex>
			<vertex><x>1090</x><y>495</y></vertex>
			<vertex><x>1090</x><y>494</y></vertex>
			<vertex><x>1090</x><y>491</y></vertex>
			<vertex><x>1091</x><y>487</y></vertex>
			<vertex><x>1092</x><y>484</y></vertex>
			<vertex><x>1091</x><y>480</y></vertex>

		</mesh>
	</province>
	<province>
		<name>egypt</name>
		<mesh>
			<vertex><x>960</x><y>418</y></vertex>
			<vertex><x>951</x><y>436</y></vertex>
			<vertex><x>949</x><y>449</y></vertex>
			<vertex><x>945</x><y>457</y></vertex>
			<vertex><x>962</x><y>468</y></vertex>
			<vertex><x>977</x><y>464</y></vertex>
			<vertex><x>1002</x><y>484</y></vertex>
			<vertex><x>1022</x><y>498</y></vertex>
			<vertex><x>1032</x><y>493</y></vertex>
			<vertex><x>1037</x><y>486</y></vertex>
			<vertex><x>1079</x><y>487</y></vertex>
			<vertex><x>1090</x><y>479</y></vertex>
			<vertex><x>1082</x><y>460</y></vertex>
			<vertex><x>1077</x><y>451</y></vertex>
			<vertex><x>1076</x><y>444</y></vertex>
			<vertex><x>1083</x><y>456</y></vertex>
			<vertex><x>1086</x><y>456</y></vertex>
			<vertex><x>1090</x><y>442</y></vertex>
			<vertex><x>1085</x><y>433</y></vertex>
			<vertex><x>1073</x><y>436</y></vertex>
			<vertex><x>1070</x><y>432</y></vertex>
			<vertex><x>1059</x><y>437</y></vertex>
			<vertex><x>1044</x><y>431</y></vertex>
			<vertex><x>1030</x><y>429</y></vertex>
			<vertex><x>1021</x><y>424</y></vertex>
			<vertex><x>1009</x><y>429</y></vertex>
			<vertex><x>1012</x><y>437</y></vertex>
			<vertex><x>1007</x><y>441</y></vertex>
			<vertex><x>988</x><y>434</y></vertex>
			<vertex><x>987</x><y>426</y></vertex>
			<vertex><x>969</x><y>425</y></vertex>
			<vertex><x>960</x><y>418</y></vertex>
		</mesh>
	</province>
	<province>
		<name>madagascar</name>
		<mesh>
			<vertex><x>1198</x><y>666</y></vertex>
			<vertex><x>1194</x><y>672</y></vertex>
			<vertex><x>1196</x><y>679</y></vertex>
			<vertex><x>1186</x><y>682</y></vertex>
			<vertex><x>1185</x><y>694</y></vertex>
			<vertex><x>1175</x><y>698</y></vertex>
			<vertex><x>1175</x><y>705</y></vertex>
			<vertex><x>1157</x><y>709</y></vertex>
			<vertex><x>1153</x><y>722</y></vertex>
			<vertex><x>1160</x><y>744</y></vertex>
			<vertex><x>1147</x><y>765</y></vertex>
			<vertex><x>1151</x><y>781</y></vertex>
			<vertex><x>1152</x><y>795</y></vertex>
			<vertex><x>1165</x><y>806</y></vertex>
			<vertex><x>1181</x><y>797</y></vertex>
			<vertex><x>1202</x><y>725</y></vertex>
			<vertex><x>1203</x><y>712</y></vertex>
			<vertex><x>1203</x><y>700</y></vertex>
			<vertex><x>1205</x><y>679</y></vertex>
			<vertex><x>1201</x><y>667</y></vertex>
